name: Custom Docker Workflow

on:
  push:
    branches:
      - main
      - latest
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Enter Docker Hub Username'
        required: true
      docker_password:
        description: 'Enter Docker Hub Password'
        required: true
      image_name:
        description: 'Enter the Docker image name (e.g., myimage)'
        required: true
        default: 'zb'
      image_tag:
        description: 'Enter the Docker image tag (e.g., latest, v1.0)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}

      - name: Build Docker image
        run: docker build . -t ${{ github.event.inputs.image_name }}

      - name: Tag Docker image with the repository name
        run: docker tag ${{ github.event.inputs.image_name }} ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}

      - name: Tag Docker image with user-specified tag
        run: docker tag ${{ github.event.inputs.image_name }} ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}

      - name: Push Docker image
        run: docker push ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}

      - name: Push user-specified tag
        run: docker push ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
